const $=id=>document.getElementById(id);
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected=Math.max(1,Math.min(63,Number(location.hash.slice(1))||1)), onlyConfirm=false;
const needs=q=>/\[(?:CONFIRM|BANK|BRANCH|FULL BRANCH|ACCOUNT HOLDER|STATEMENT|NAME AND)/.test(q.answer);
$('confirm-count').textContent=GUIDE.questions.filter(needs).length;
function renderList(){const terms=$('search').value.toLowerCase().split(',').map(t=>t.trim()).filter(Boolean);const rows=GUIDE.questions.filter(q=>(!onlyConfirm||needs(q))&&(!terms.length||terms.some(term=>`${q.id} ${q.question} ${q.answer} ${q.group}`.toLowerCase().includes(term))));const groups=[...new Set(rows.map(q=>q.group))].map(name=>({name,rows:rows.filter(q=>q.group===name)}));const columns=Array.from({length:innerWidth>=1100?4:innerWidth>=740?3:innerWidth>=520?2:1},()=>({groups:[],load:0}));groups.map((g,index)=>({...g,index})).sort((a,b)=>b.rows.length-a.rows.length).forEach(g=>{const col=columns.reduce((a,b)=>a.load<=b.load?a:b);col.groups.push(g);col.load+=g.rows.length+1.5});$('questions').innerHTML=rows.length?columns.sort((a,b)=>Math.min(...a.groups.map(g=>g.index))-Math.min(...b.groups.map(g=>g.index))).map(col=>'<div class="question-column">'+col.groups.sort((a,b)=>a.index-b.index).map(g=>`<section class="topic-group"><h2>${escape(g.name)}</h2>`+g.rows.map(q=>`<button class="q" data-id="${q.id}"><span class="num">${String(q.id).padStart(2,'0')}</span><span class="text">${escape(q.question)}</span>${needs(q)?'<span class="dot" title="Details to confirm"></span>':''}</button>`).join('')+'</section>').join('')+'</div>').join(''):'<p class="empty">No matching questions. Try a topic, a keyword, or a question number.</p>';$('count').textContent=terms.length||onlyConfirm?`${rows.length} of 63 questions`:'63 questions · 11 topics';$('clear').hidden=!terms.length&&!onlyConfirm;}
function openDialog(){if(!$('answer-dialog').open)$('answer-dialog').showModal();document.body.classList.add('modal-open');$('main').scrollTop=0;}
function format(answer){let table='';const tableStart=answer.indexOf('Period\nBefore scholarship');if(tableStart>=0){const end=answer.indexOf('Estimates assume',tableStart);const cells=answer.slice(tableStart,end).trim().split('\n');table='<div class=table-wrap><table><thead><tr>'+cells.slice(0,3).map(c=>'<th>'+escape(c)+'</th>').join('')+'</tr></thead><tbody>';for(let i=3;i<cells.length;i+=3)table+='<tr>'+cells.slice(i,i+3).map(c=>'<td>'+escape(c)+'</td>').join('')+'</tr>';table+='</tbody></table></div>';answer=answer.slice(0,tableStart)+'\nTABLE_SLOT\n'+answer.slice(end)}let lines=answer.split('\n'),chunks=[],buf=[];const flush=()=>{if(buf.length){chunks.push('<p>'+escape(buf.join(' ')).replace(/\[[A-Z][^\]]*\]/g,'<mark>$&</mark>')+'</p>');buf=[]}};for(const line of lines){if(line==='TABLE_SLOT'){flush();chunks.push(table)}else if(/^Semester [1-4]$/.test(line)){flush();chunks.push('<h3>'+line+'</h3>')}else if(line.startsWith('- ')){flush();chunks.push('<p style="font-size:.85em">'+escape(line)+'</p>')}else buf.push(line)}flush();return chunks.join('')}
function show(id,updateHash=true){selected=id;$('previous').hidden=false;$('next').hidden=false;const q=GUIDE.questions[id-1];$('topic').textContent=q.group;$('position').textContent=`${id} / 63`;$('number').textContent=`QUESTION ${String(id).padStart(2,'0')}`;$('title').textContent=q.question;$('pending').hidden=!needs(q);$('answer').innerHTML=format(q.answer);$('source-note').innerHTML=`From the original guide · <a href="source.pdf#page=${q.page}" target="_blank">PDF page ${q.page} ↗</a>`;$('previous').disabled=id===1;$('next').disabled=id===63;if(updateHash)history.replaceState(null,'','#'+id);openDialog();}
$('questions').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)show(Number(b.dataset.id))});$('search').addEventListener('input',renderList);$('all').onclick=()=>{onlyConfirm=false;$('all').classList.add('active');$('confirm').classList.remove('active');renderList()};$('confirm').onclick=()=>{onlyConfirm=true;$('confirm').classList.add('active');$('all').classList.remove('active');renderList()};$('clear').onclick=()=>{$('search').value='';$('all').click()};$('previous').onclick=()=>show(selected-1);$('next').onclick=()=>show(selected+1);
$('notes').onclick=()=>{$('topic').textContent='PREPARATION NOTES';$('position').textContent='Original guide · pages 15–16';$('number').textContent='REFERENCE';$('pending').hidden=true;$('title').textContent='Sources & details to confirm';$('answer').innerHTML=GUIDE.notes.map((n,i)=>`<h3>${i===0?'Sources and reference notes':'Information needed to finish your guide'}</h3><div class="source-list">${escape(n).replace(/\n/g,'<br>')}</div>`).join('')+'<h3>Source links from the PDF</h3><ol class="source-list">'+GUIDE.links.map(url=>`<li><a href="${escape(url)}" target="_blank" rel="noopener">${escape(url)}</a></li>`).join('')+'</ol>';$('source-note').innerHTML='<a href="source.pdf#page=15" target="_blank">Read notes in the PDF ↗</a>';$('previous').hidden=true;$('next').hidden=true;openDialog();};
$('close').onclick=()=>$('answer-dialog').close();$('answer-dialog').addEventListener('close',()=>{document.body.classList.remove('modal-open');history.replaceState(null,'',location.pathname+location.search)});$('answer-dialog').addEventListener('click',e=>{if(e.target===$('answer-dialog')){const r=$('answer-dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('answer-dialog').close()}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!$('answer-dialog').open&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('search').focus()}if(e.key==='Escape'&&!$('answer-dialog').open){$('search').value='';$('all').click();$('search').blur()}});window.addEventListener('hashchange',()=>{const id=Number(location.hash.slice(1));if(id>=1&&id<=63)show(id,false)});window.addEventListener('resize',renderList);renderList();if(/^#(?:[1-9]|[1-5][0-9]|6[0-3])$/.test(location.hash))show(selected,false);
